sudo: required
services:
  - docker
language: 
  - python: 3.7
install:
  - pip install --upgrade pip==18.0
  - pip install pipenv
  - pipenv install
# command to run tests
# script:
# unit test
# – python -m pytest -v
# linting test
# – flake8
after_success:
  - sh .travis/deploy_dockerhub.sh
